cuda:0
current epoch is 0
Traceback (most recent call last):
  File "/home/baebro/Downloads/pycharm-2021.3/plugins/python/helpers/pydev/pydevd.py", line 1483, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/home/baebro/Downloads/pycharm-2021.3/plugins/python/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/home/baebro/nipa_ws/nipaproj_ws/model/train.py", line 165, in <module>
    main()
  File "/home/baebro/nipa_ws/nipaproj_ws/model/train.py", line 96, in main
    anchor_emb = model(anchor)
  File "/home/baebro/anaconda3/envs/mp/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/baebro/anaconda3/envs/mp/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/baebro/nipa_ws/nipaproj_ws/model/model.py", line 50, in forward
    x,  = self.lstm1(x)
ValueError: too many values to unpack (expected 1)
Traceback (most recent call last):
  File "/home/baebro/Downloads/pycharm-2021.3/plugins/python/helpers/pydev/pydevd.py", line 2173, in <module>
    main()
  File "/home/baebro/Downloads/pycharm-2021.3/plugins/python/helpers/pydev/pydevd.py", line 2164, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/home/baebro/Downloads/pycharm-2021.3/plugins/python/helpers/pydev/pydevd.py", line 1476, in run
    return self._exec(is_module, entry_point_fn, module_name, file, globals, locals)
  File "/home/baebro/Downloads/pycharm-2021.3/plugins/python/helpers/pydev/pydevd.py", line 1483, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/home/baebro/Downloads/pycharm-2021.3/plugins/python/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/home/baebro/nipa_ws/nipaproj_ws/model/train.py", line 165, in <module>
    main()
  File "/home/baebro/nipa_ws/nipaproj_ws/model/train.py", line 96, in main
    anchor_emb = model(anchor)
  File "/home/baebro/anaconda3/envs/mp/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/baebro/anaconda3/envs/mp/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/baebro/nipa_ws/nipaproj_ws/model/model.py", line 50, in forward
    x,  = self.lstm1(x)
ValueError: too many values to unpack (expected 1)
